
package clientDDO;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "SchoolServerImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:4030/school?wsdl")
public class SchoolServerImplService
        extends Service {

    private final static URL SCHOOLSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCHOOLSERVERIMPLSERVICE_EXCEPTION;
    private final static QName SCHOOLSERVERIMPLSERVICE_QNAME = new QName("http://server/", "SchoolServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4030/school?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCHOOLSERVERIMPLSERVICE_WSDL_LOCATION = url;
        SCHOOLSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public SchoolServerImplService() {
        super(__getWsdlLocation(), SCHOOLSERVERIMPLSERVICE_QNAME);
    }

    public SchoolServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCHOOLSERVERIMPLSERVICE_QNAME, features);
    }

    public SchoolServerImplService(URL wsdlLocation) {
        super(wsdlLocation, SCHOOLSERVERIMPLSERVICE_QNAME);
    }

    public SchoolServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCHOOLSERVERIMPLSERVICE_QNAME, features);
    }

    public SchoolServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchoolServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns SchoolServer
     */
    @WebEndpoint(name = "SchoolServerImplPort")
    public SchoolServer getSchoolServerImplPort() {
        return super.getPort(new QName("http://server/", "SchoolServerImplPort"), SchoolServer.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SchoolServer
     */
    @WebEndpoint(name = "SchoolServerImplPort")
    public SchoolServer getSchoolServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "SchoolServerImplPort"), SchoolServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCHOOLSERVERIMPLSERVICE_EXCEPTION != null) {
            throw SCHOOLSERVERIMPLSERVICE_EXCEPTION;
        }
        return SCHOOLSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
